watch:
  directories:
    - src
    - tests
  fileMask: '*.php'
notifications:
  passingTests: true
  failingTests: true
phpunit:
  binaryPath: ~/.composer/vendor/phpunit/phpunit/phpunit
  arguments: '--stop-on-failure'
